authorization: add branch pull request checks
pagarme/hubot-deploy pull request #8
Opened 2018-12-21 18:46 UTC by Otavioensa

Only branches with open and mergeable pull requests can be deployed.

These pull requests need to be approved by specific people, but this
rule can be implemented on github only, since `mergeable_state` on api
returns if it was approved specifically by who it should be. It returns
if it has no conflicts too.

- Tests already made: 
- [x] This branch has no pull request 
- [x] This branch has many pull requests 
- [ ] This branch has a blocked pull request 
  - [x] with non valid approvers
  - [] with valid approver

2018-12-27 16:43 UTC, moog commented on Cakefile
> +    throw err if err
Por que foi preciso mover essa linha?

2018-12-27 16:47 UTC, flyingluscas commented on Cakefile
> +    throw err if err
@moog porque quando os testes falhavam os logs não exibiam qual teste estava quebrando, isso porque o console estava depois do throw :/

2018-12-30 03:18 UTC, macabeus requested changes

2018-12-30 03:18 UTC, macabeus commented on src/pull_request.coffee
> +    @request.get path, params, (err, status, body) ->
`body`  não é um nome tão expressivo assim. Creio que poderia ser algo como `pulls`

2018-12-30 03:18 UTC, macabeus commented on src/pull_request.coffee
> +    that = this
Uma alternativa que considero mais legível que o uso do `that` é definir previamente todas as variáveis do `this` como sendo do escopo local. Isso inclusive estava sendo feito em outras partes do código.

Por exemplo, aqui ficaria:

```
checkOpenPullRequests: (resolve, reject) ->
  checkPullRequestMergeableState = @checkPullRequestMergeableState

  ...

    return checkPullRequestMergeableState body[0].number, resolve, reject
```

Fica mais verboso, mas também mais explícito.

2018-12-30 03:18 UTC, macabeus commented on src/pull_request.coffee
> +    that = this
O que falei acima do return `that` vale aqui também. No caso, teria que declarar:

```
branch = @branch
checkOpenPullRequests = @checkOpenPullRequests
```

2018-12-30 03:18 UTC, macabeus commented on test/pull_request.coffee
> +	  it "should return error if the branch has no pull request", () ->
Porque aqui está com todo esse nível de endentação?

2018-12-30 03:18 UTC, macabeus commented on src/deployment.coffee
> +Octonode = require("octonode")
Removeu essa tabelação sem sentido ❤️

2018-12-30 03:18 UTC, macabeus commented on src/scripts/deploy.coffee
> +            2. Missing code owners review"
Creio que seja mais legível escrever multiline strings assim:

```
msg.reply """
  This branch has a blocked pull request (branch name: #{ref})
  Possible causes:
    1. CI failing
    2. Missing code owners review
"""
```

2018-12-30 03:18 UTC, macabeus commented on src/pull_request.coffee
> +      return states.BlockedPullRequest
[Tem vários outros status possíveis além desses 2](https://developer.github.com/v4/enum/mergestatestatus/). Por acaso faria sentido olhá-los? Como negar se for `unknown`

2018-12-30 03:18 UTC, macabeus commented on src/pull_request.coffee
> +      head: "pagarme:#{@branch}"
Realmente faz sentido hardcodar o nome `pagarme` aqui?

2018-12-31 12:14 UTC, flyingluscas commented on src/pull_request.coffee
> +      return states.BlockedPullRequest
@macabeus Ótima pergunta, para o propósito desse PR acredito que não, até porque boa parte dessas validações já são feitas logo em seguida no `POST /deployments`.

2019-01-02 16:20 UTC, darakeon commented on src/pull_request.coffee
> +      return states.BlockedPullRequest
Talvez devêssemos até tirar o dirty, a verificação atual também vê isso, não?

2019-01-02 16:42 UTC, flyingluscas commented on src/pull_request.coffee
> +      return states.BlockedPullRequest
@darakeon sim! acho que podemos tirar, porque isso já é verificado depois.

2019-01-02 18:20 UTC, jeanaugustoos commented on test/pull_request.coffee
> +	  it "should return error if the branch has no pull request", () ->
A indentação está certa aqui?

2019-01-02 18:22 UTC, jeanaugustoos commented on src/scripts/deploy.coffee
> +  #######g####################################################################
```suggestion
   ############################################################################
```

2019-01-02 18:37 UTC, flyingluscas commented on src/scripts/deploy.coffee
> +  #######g####################################################################
é breaking change isso, nao pode hehhehheehe

2019-01-02 19:44 UTC, jeanaugustoos approved these changes

2019-01-02 20:11 UTC, mccraveiro commented on src/pull_request.coffee
> +    @request.get path, params, (err, status, pulls) ->
Não precisa do `that = this` se usar `=>` aqui!

```suggestion
    @request.get path, params, (err, status, pulls) =>
```

2019-01-02 20:15 UTC, mccraveiro commented on src/pull_request.coffee
> +        return resolve isValidList
Shouldn't you use `reject` here?

2019-01-02 20:18 UTC, mccraveiro commented on src/pull_request.coffee
> +    @request.get path, {}, (err, status, body) ->
You don't need `that = this` if you use `=>` here :)

```suggestion
    @request.get path, {}, (err, status, body) =>
```

2019-01-02 20:25 UTC, mccraveiro commented on src/pull_request.coffee
> +    new Promise (resolve, reject) ->
You don't need `that = this` if you use `=>` here :)

```suggestion
    new Promise (resolve, reject) =>
```

2019-01-03 02:48 UTC, macabeus commented on src/pull_request.coffee
> +    new Promise (resolve, reject) ->
Nossa!! Não sabia que coffescript tinha arrow function tal como ES6! Isso teria me ajudado muito antes 😱

2019-01-03 12:31 UTC, flyingluscas commented on src/pull_request.coffee
> +        return resolve isValidList
@mccraveiro I don't see why use a reject here, this is not an error, is just another path that will lead to an specific state of the pull request, make sense?

2019-01-03 13:05 UTC, mccraveiro approved these changes

2019-01-03 13:05 UTC, mccraveiro commented on src/scripts/deploy.coffee
> +          when pullrequest.states.NoPullRequests
IMHO these should be custom error objects so you could throw them. Like this:

```coffee
class NoPullRequests extends Error
  constructor: (message) ->
    super(message)

deployment.checkPullRequestState()
  .then () -> startDeployProcess()
  .catch (err) ->
    if err instanceof NoPullRequests
      msg.reply "This branch has no pull request (branch name: #{ref})"
    else 
      console.log err
```

2019-01-03 13:23 UTC, merged